#!/usr/bin/env python3
"""Builds the Kitchen Display's own mark: the octopus, broadcasting.

    python tools/generate_kds_mark.py        (also run by generate_brand_assets.py)

The KDS is a different app from the POS and must not wear the same icon — on a
kitchen tablet sitting next to a till, two identical icons is a guessing game.
It is also the one app whose whole job starts with PAIRING: it sits on the LAN
and waits for a till to find it. So its mark is the same octopus with a Wi-Fi
signal radiating from the tip of its raised right antenna. The antenna's ball
terminal doubles as the signal's dot, which is what makes this read as one
drawing rather than a logo with a sticker on it.

Nothing here draws an octopus. The geometry is READ from img/icon-mark.svg and
the plate from img/icon.svg, so the two marks can never drift apart: redraw the
octopus there and this one follows on the next run.

Writes (both GENERATED — do not hand-edit):
    img/icon-kds.svg        the KDS mark on its plate
    img/icon-kds-mark.svg   the KDS mark alone, transparent
"""

from __future__ import annotations

import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
IMG = ROOT / "img"

BRAND_BLUE = "#389DCB"

# The octopus shrinks and steps down-left to make room for the signal, and the
# pair is then centred as ONE figure. Worked out against the octopus's own box
# (x 105-407, y 67-448 in icon-mark.svg) and the arcs' reach, so the combined
# drawing sits on the plate's centre rather than the octopus alone doing so.
OCTOPUS_SCALE = 0.8
OCTOPUS_SHIFT = (10.0, 100.0)

# The right antenna's ball terminal, in icon-mark.svg's own coordinates. The
# signal radiates from here.
ANTENNA_TIP = (369.0, 94.0)

# Three arcs, like every Wi-Fi glyph people already know. Radii measured from
# the ball's centre, packed so every gap — ball to first ring, ring to ring —
# is about one stroke wide. Wider gaps read fine at 512px and fall apart at
# 32px, where the rings detach and float in the corner as a separate blob.
ARC_RADII = (46.0, 76.0, 106.0)
# Matches the tentacles AFTER scaling (20 x 0.8), so the signal is drawn with
# the same pen as the octopus rather than sitting on it as a heavier sticker.
ARC_STROKE = 16.0

# The fan opens up-and-right, AWAY from the antenna's own arm (which leaves the
# ball heading straight down) so a ring never crosses the octopus. 70 degrees
# rather than the textbook 90: a narrower fan keeps the outer ring clear of
# the plate's rounded corner at every icon size.
ARC_FROM_DEG = -80.0
ARC_TO_DEG = -10.0


def _octopus_body() -> str:
    """icon-mark.svg's drawing, minus its <svg> wrapper and its comments."""
    text = (IMG / "icon-mark.svg").read_text(encoding="utf-8")
    text = re.sub(r"<!--.*?-->", "", text, flags=re.S)
    body = re.search(r"<svg[^>]*>(.*)</svg>", text, flags=re.S)
    if not body:
        raise SystemExit("img/icon-mark.svg: no <svg> body found")
    return body.group(1).strip()


def _plate() -> str:
    """icon.svg's <defs> and plate rects — the same plate the POS icon sits on."""
    text = (IMG / "icon.svg").read_text(encoding="utf-8")
    text = re.sub(r"<!--.*?-->", "", text, flags=re.S)
    defs = re.search(r"<defs>.*?</defs>", text, flags=re.S)
    rects = re.findall(r"<rect\b[^>]*/>", text, flags=re.S)
    if not defs or len(rects) < 2:
        raise SystemExit("img/icon.svg: plate <defs>/<rect> not found")
    return defs.group(0) + "\n  " + "\n  ".join(rects[:2])


def _signal() -> str:
    """The three arcs, centred on where the antenna tip lands after the shift."""
    sx, sy = OCTOPUS_SHIFT
    cx = sx + ANTENNA_TIP[0] * OCTOPUS_SCALE
    cy = sy + ANTENNA_TIP[1] * OCTOPUS_SCALE
    a0, a1 = math.radians(ARC_FROM_DEG), math.radians(ARC_TO_DEG)

    def pt(r: float, a: float) -> str:
        return f"{cx + r * math.cos(a):.1f} {cy + r * math.sin(a):.1f}"

    # sweep-flag 1: with SVG's y axis pointing DOWN, increasing the angle from
    # -80 to -10 degrees travels clockwise.
    paths = "\n    ".join(
        f'<path d="M {pt(r, a0)} A {r:g} {r:g} 0 0 1 {pt(r, a1)}" />'
        for r in ARC_RADII
    )
    return (
        f'<g fill="none" stroke="{BRAND_BLUE}" stroke-width="{ARC_STROKE:g}" '
        f'stroke-linecap="round">\n    {paths}\n  </g>'
    )


def _svg(*, plated: bool) -> str:
    sx, sy = OCTOPUS_SHIFT
    octopus = _octopus_body().replace("\n", "\n    ")
    parts = [
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" '
        'width="512" height="512">',
        "  <!-- GENERATED by tools/generate_kds_mark.py from img/icon-mark.svg"
        + (" and img/icon.svg" if plated else "")
        + ".\n       Do not edit: change the octopus there, or the signal in"
        " that script. -->",
    ]
    if plated:
        parts.append("  " + _plate())
    parts += [
        f'  <g transform="translate({sx:g} {sy:g}) scale({OCTOPUS_SCALE:g})">',
        "    " + octopus,
        "  </g>",
        "  " + _signal(),
        "</svg>",
        "",
    ]
    return "\n".join(parts)


def build() -> tuple[Path, Path]:
    """Writes both KDS SVGs and returns their paths (plated, bare)."""
    plated_path = IMG / "icon-kds.svg"
    bare_path = IMG / "icon-kds-mark.svg"
    plated_path.write_text(_svg(plated=True), encoding="utf-8")
    bare_path.write_text(_svg(plated=False), encoding="utf-8")
    return plated_path, bare_path


if __name__ == "__main__":
    for path in build():
        print(f"  {path.relative_to(ROOT)}")
